### ISSUE TITLE
Angel icon not displayed in Chromium-based browsers

### ISSUE THREAD

**Issue by n-st** [engelsystem/engelsystem.de#15]
The [new design uses the CSS `mask` property](https://github.com/engelsystem/engelsystem.de/commit/f01ecce8#diff-25d04eec60d077990ee7cfe2aa8be3b381f65f508e3721e827b5efb8ba07e972R8-R9), which is currently [not fully supported by Chromium-based browsers](https://caniuse.com/css-masks).

This prevents the angel icon from showing correctly, instead showing a solid black or white box, depending on the font colour:  
![Screenshot_2023-08-21_18-49-33](https://github.com/engelsystem/engelsystem.de/assets/2692085/568851dc-0e03-47f9-8105-abc91106e1bf)

A possible workaround would be to duplicate the `mask` property as `-webkit-mask` (and likewise `mask-size` as `-webkit-mask-size`).

**Comment by MyIgel** [comment]
Thats right & its fixed in 73311ff3a4472bf1197b339024b612e39e2cb90a which just needs to be deployed by @msquare or @leaneb ^^
